#!/usr/bin/env python3
import os
import sys
Mode = ""

if len(sys.argv) == 2:
	if sys.argv[1] == "cross-compile":
		Mode = "Cross ARM"
#/usr/lib/x86_64-linux-gnu/qt5/mkspecs 			# VIEW ALL ARCH
#qmake -makefile <your-project.pro> -spec linux-clang   # TO COMPILE
#arm-linux-gnueabihf-g++

#for fedora qmake-qt5


if Mode == "Cross ARM":
	for each in os.listdir("/usr/lib/x86_64-linux-gnu/qt5/mkspecs/"):
		print(each)
	Comp = input("choose compiler : ")
	print(Comp)
	
	os.system("qmake -makefile Server.pro -spec " + Comp + " && make")
else:
	os.system("qmake-qt5 -makefile zk-data.bluekenny.pro && make")
if os.path.exists("Makefile"): os.remove("Makefile")
for each in os.listdir("./"):
	if str(each).endswith(".o") or each == ".qmake.stash" or each == "manifest.json":
		os.remove(each)

#print("\n")
#print("\n")
#os.system("./Server")


#echo "\n\n"
#echo "i686-w64-mingw32-g++"
#i686-w64-mingw32-g++ -o Server.exe Server.cpp
